### ISSUE TITLE
Figure out ideal CLI UI

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/lazyledger-app#38]
The latest [addition](https://github.com/lazyledger/lazyledger-app/pull/32) to the cli follows the format of the rest of the starport generated cli, except it use relies on hex encoding for accepting the two raw byte arguments. While most users are not going to be using the cli, we still need to figure an ideal, or at least consistent, UI/UX.

**Comment by adlerjohn** [comment]
What encoding does the rest of the CLI use?

**Comment by liamsi** [comment]
https://github.com/lazyledger/lazyledger-app/pull/32#discussion_r582143864
