### ISSUE TITLE
Implement PayForMessage client code 

### ISSUE THREAD

**Issue by evan-forbes** [CelestiaOrg/lazyledger-app#92]
Some client code for for signing and broadcasting `WirePayForMessage`s was implemented in [#76](https://github.com/lazyledger/optimint/pull/76), and per the suggestion in this comment https://github.com/lazyledger/optimint/pull/76#discussion_r647834782 , we should keep that code here. It might also be nice to change up the API slightly to be a tad more general, and maybe even reuse that code in the already implemented cli.

**Comment by liamsi** [comment]
> It might also be nice to change up the API slightly to be a tad more general, and maybe even reuse that code in the already implemented cli.

Can you point me to the existing cli code that does a similar job? The relation between the two are not really clear to me. Also, can't optimint use the existing code in the cli instead @tzdybal? Sorry if these are somewhat naive questions and I'm a bit late to the party. I'm just wondering if there is a more simple and canonical way here. That said, I think it's OK to merge #94 to unblock the optimint work and come back to that later.

**Comment by tzdybal** [comment]
Calling commandline instead of using "proper" RPC is definitely doable. The ugly part will be parsing the command output.

**Comment by evan-forbes** [comment]
> Can you point me to the existing cli code that does a similar job?

yeah, so the app's [PFM cli](https://github.com/lazyledger/lazyledger-app/blob/6cd6c757a5ccd8157f9a2419cfe652f446907afb/x/lazyledgerapp/client/cli/payformessage.go#L75-L76) code calls this [signing and broadcasting code](https://github.com/lazyledger/cosmos-sdk/blob/3addd7f65d1c35f76716d67641ee629b01f5b9c7/client/tx/tx.go#L75-L137) which is basically doing exactly what we want, except it's using the cobra cmd flags as input. Specifically, it's using something called a [`Factory`](https://github.com/lazyledger/cosmos-sdk/blob/3addd7f65d1c35f76716d67641ee629b01f5b9c7/client/tx/factory.go#L13-L30). The client code in #94 essentially takes the bare minimum from that code and allows for easy signing of `sdk.Msg`s, but uses normal programatic inputs instead of cli flags.

I initially thought that we could simplify the cli code a bit by using #94, but I no longer think that is worth it, unless we wanted to make a cli that doesn't rely on running a local node.
